// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiPlZsPbVSciDxwly-k0hOpcI-3RXDtLA',
    appId: '1:341672044377:web:3aa6b70c17693b0a4b0e48',
    messagingSenderId: '341672044377',
    projectId: 'prem-s-fprm',
    authDomain: 'prem-s-fprm.firebaseapp.com',
    storageBucket: 'prem-s-fprm.firebasestorage.app',
    measurementId: 'G-8KJX247TVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTH2_bPpEejArveKQkUwb40-NjfJiFg5E',
    appId: '1:341672044377:android:0374a15d47b1ad964b0e48',
    messagingSenderId: '341672044377',
    projectId: 'prem-s-fprm',
    storageBucket: 'prem-s-fprm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA03zj9TnnKHIGyZPI4a7fuF8o04ZVY3nw',
    appId: '1:341672044377:ios:77e1588318d233ae4b0e48',
    messagingSenderId: '341672044377',
    projectId: 'prem-s-fprm',
    storageBucket: 'prem-s-fprm.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA03zj9TnnKHIGyZPI4a7fuF8o04ZVY3nw',
    appId: '1:341672044377:ios:77e1588318d233ae4b0e48',
    messagingSenderId: '341672044377',
    projectId: 'prem-s-fprm',
    storageBucket: 'prem-s-fprm.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiPlZsPbVSciDxwly-k0hOpcI-3RXDtLA',
    appId: '1:341672044377:web:b084cc3433e3baad4b0e48',
    messagingSenderId: '341672044377',
    projectId: 'prem-s-fprm',
    authDomain: 'prem-s-fprm.firebaseapp.com',
    storageBucket: 'prem-s-fprm.firebasestorage.app',
    measurementId: 'G-ETRZCYY96P',
  );
}
